### ISSUE TITLE
how to modify the entrypoint.sh in container

### ISSUE THREAD

**Issue by zhangr1008** [ehfd/docker-nvidia-egl-desktop#10]
Hi,
If I modified the /etc/entrypoint.sh in the container, then restart the container, the process will be less than first start, what's the problem?

user@c907d6e6b0c7:~$ ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
user           1       0  1 04:44 pts/0    00:00:00 /usr/bin/python3 /usr/bin/supervisord
user           8       1  0 04:44 pts/0    00:00:00 /bin/bash /etc/entrypoint.sh
root          29       1  0 04:44 ?        00:00:00 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups
message+      43       1  0 04:44 ?        00:00:00 /usr/bin/dbus-daemon --system
user         105       8 51 04:44 pts/0    00:00:09 /usr/bin/java -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048
user         106       8  0 04:44 pts/0    00:00:00 guacd -b 0.0.0.0 -f
user         161       0  2 04:44 pts/1    00:00:00 /bin/bash
user         172     161  0 04:44 pts/1    00:00:00 ps -ef

Cannot see the VNC like processes anymore, any ideas?
Thanks a lot.

**Comment by zhangr1008** [comment]
It is not the modified entrypoint.sh issue maybe. If I stopped and started the same container, the processes inside would be left few. Any suggestion if I want to stop and start the container?

Thanks a lot.

**Comment by ehfd** [comment]
You should build your own new container after editing the entrypoint.sh and Dockerfile, else it might lead to issues that cannot be assisted. The docker stop command should work otherwise.

**Comment by zhangr1008** [comment]
The docker stop can't work:(. If I just pull and run the container first time, everything goes well. As I stopped the container and then started it, things changed. VNC server cannot start anymore.

**Comment by ehfd** [comment]
So yeah, I think that you should clone this repository with git, edit Dockerfile and entrypoint.sh, then do `docker build .` then try starting the container that got built that way.
And if something goes wrong, I could try to see what's wrong.

**Comment by zhangr1008** [comment]
Thanks a lot. I found the issue. The VNC server can't be started after the container restart. So I should delete the /tmp/.X* files before restart the container, or add the "rm -rf /tmp/.X*" in the entrypoint.sh file.

**Comment by ehfd** [comment]
Thanks, I'll make sure to include that in the next release.

**Comment by ehfd** [comment]
Fixed in commit d9eee15676a13e1b35e481827f7f48bcdeadebeb.
