### ISSUE TITLE
How to have GPU-based rendering in docker console?

### ISSUE THREAD

**Issue by jeasinema** [ehfd/docker-nvidia-egl-desktop#14]
Hi,

Thanks for this great project. It helps a lot and I really appreciate it. I follow the instructions to run that docker container and log in through webVNC. I can confirm that the GPU-based is working as I got the following output:

```
user@351d9e1b605d:/opt/VirtualGL/bin$ ./glxspheres64 
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0x11 (8/8/8/0)
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
1041.901382 frames/sec - 1162.761942 Mpixels/sec
1005.491010 frames/sec - 1122.127967 Mpixels/sec
```

However, when I try to use login to that container through docker console instead, the rendering seems to happen on CPU instead.

This is how I log in to the container through docker console:
```bash
docker exec -it <container_id> /bin/bash
```
And the output for the same command:
```
user@351d9e1b605d:/opt/VirtualGL/bin$ ./glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0x13d (8/8/8/0)
Visual ID of window: 0x3d0
Context is Direct
OpenGL Renderer: llvmpipe (LLVM 12.0.0, 256 bits)
71.574763 frames/sec - 79.877436 Mpixels/sec
```
I understand there might be some extra setups if I go through the console instead of webVNC. Can you help me with a pointer?

LMK if you need more information from me.

**Comment by jeasinema** [comment]
As a side note, the GPU rendering will stop working if I use `root` user instead, even when log in through webVNC:

```
user@351d9e1b605d:/opt/VirtualGL/bin$ sudo -i
user@351d9e1b605d:/opt/VirtualGL/bin$ ./glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0x13d (8/8/8/0)
Visual ID of window: 0x3d0
Context is Direct
OpenGL Renderer: llvmpipe (LLVM 12.0.0, 256 bits)
71.574763 frames/sec - 79.877436 Mpixels/sec
```

**Comment by ehfd** [comment]
Please append `vglrun` to all commands that you want to accelerate. Since the Desktop Environment was run using vglrun in the first place, commands run from the GUI will work without them.
For example:
`sudo vglrun glxgears -info`

**Comment by jeasinema** [comment]
@ehfd Thank you for the reply! Here is what I got:
```
(base) user@351d9e1b605d:/opt/VirtualGL/bin$ sudo vglrun ./glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0x13d (8/8/8/0)
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: llvmpipe (LLVM 12.0.0, 256 bits)
52.943677 frames/sec - 59.085144 Mpixels/sec
```
I suppose the rendering still happens on CPU? (I tried with `sudo` but basically, the output is the same as above)

**Comment by jeasinema** [comment]
Finally got it running. I need to set these env variables:
```
export VGL_REFRESHRATE=60
export VGL_ISACTIVE=1
export VGL_DISPLAY=egl
export VGL_WM=1
```

**Comment by ehfd** [comment]
`vglrun glxgears -info` in the console now works correctly without any additional environment variables.
