### ISSUE TITLE
Question regarding building a pod based on this image

### ISSUE THREAD

**Issue by pengzhi1998** [ehfd/docker-nvidia-egl-desktop#17]
Dear @ehfd, thank you so much for this great repo. You really saved my life!

But I have a few questions regarding the images:
1. As I'm training some deep learning models using Unity simulation (it has some renderings and visual observations), the remote server with a GUI would be truly helpful. In this case, if I build my pod/job to train my networks with your configuration YAML files: **_xgl.yml_** or **_egl.yml_** (both provide Vulkan and OpenGL), I don't need to install or deal with anything like Xvfb right? And from the document, I could directly use my (client) web browser to open the UI similar to VNC?
2. However, when using these two YAML files to create my pod, both failed with the status `CreateContainerConfigError`. Do I need to modify anything in your example YAML files? Or is this error caused by yesterday's Nautilus broken or corruption issues? 

Thank you again. Look forward to your reply!

**Comment by ehfd** [comment]
Do you have Discord?
https://discord.gg/wDNGDeSW5F
Matrix has a bit of an issue which prevents communicating with you.

**Comment by pengzhi1998** [comment]
Thank you so much for your quick reply. I thought it was my connection problem. 
I have a Discord account. And when clicking on the link, it shows _mr_space_man_ is inviting me to **_Selkies OSS_**. Is that you?
